/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphologyNode
 */
export interface GraphologyNode {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphologyNode
     */
    attributes: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof GraphologyNode
     */
    key: number;
}

/**
 * Check if a given object implements the GraphologyNode interface.
 */
export function instanceOfGraphologyNode(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "key" in value;

    return isInstance;
}

export function GraphologyNodeFromJSON(json: any): GraphologyNode {
    return GraphologyNodeFromJSONTyped(json, false);
}

export function GraphologyNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphologyNode {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': json['attributes'],
        'key': json['key'],
    };
}

export function GraphologyNodeToJSON(value?: GraphologyNode | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': value.attributes,
        'key': value.key,
    };
}

