/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetadataShort } from './MetadataShort';
import {
    MetadataShortFromJSON,
    MetadataShortFromJSONTyped,
    MetadataShortToJSON,
} from './MetadataShort';

/**
 * This serializer activates the tracking of
 * serialized objects.
 * It adds the `_represented` (not to use), the `represented`
 * and `reset` methods.
 * Important: it overrides the `to_representation` common method
 * of `Serializer` objects.
 * @export
 * @interface GraphObject
 */
export interface GraphObject {
    /**
     * 
     * @type {string}
     * @memberof GraphObject
     */
    readonly graphObjectType: string;
    /**
     * 
     * @type {number}
     * @memberof GraphObject
     */
    readonly id: number;
    /**
     * 
     * @type {Array<MetadataShort>}
     * @memberof GraphObject
     */
    metadata?: Array<MetadataShort>;
}

/**
 * Check if a given object implements the GraphObject interface.
 */
export function instanceOfGraphObject(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "graphObjectType" in value;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function GraphObjectFromJSON(json: any): GraphObject {
    return GraphObjectFromJSONTyped(json, false);
}

export function GraphObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphObjectType': json['graph_object_type'],
        'id': json['id'],
        'metadata': !exists(json, 'metadata') ? undefined : ((json['metadata'] as Array<any>).map(MetadataShortFromJSON)),
    };
}

export function GraphObjectToJSON(value?: GraphObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': value.metadata === undefined ? undefined : ((value.metadata as Array<any>).map(MetadataShortToJSON)),
    };
}

