/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GraphologyLink
 */
export interface GraphologyLink {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GraphologyLink
     */
    attributes: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof GraphologyLink
     */
    source: number;
    /**
     * 
     * @type {number}
     * @memberof GraphologyLink
     */
    target: number;
}

/**
 * Check if a given object implements the GraphologyLink interface.
 */
export function instanceOfGraphologyLink(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attributes" in value;
    isInstance = isInstance && "source" in value;
    isInstance = isInstance && "target" in value;

    return isInstance;
}

export function GraphologyLinkFromJSON(json: any): GraphologyLink {
    return GraphologyLinkFromJSONTyped(json, false);
}

export function GraphologyLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphologyLink {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attributes': json['attributes'],
        'source': json['source'],
        'target': json['target'],
    };
}

export function GraphologyLinkToJSON(value?: GraphologyLink | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attributes': value.attributes,
        'source': value.source,
        'target': value.target,
    };
}

