/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GroupEnum = {
    Nodes: 'nodes',
    Edges: 'edges'
} as const;
export type GroupEnum = typeof GroupEnum[keyof typeof GroupEnum];


export function GroupEnumFromJSON(json: any): GroupEnum {
    return GroupEnumFromJSONTyped(json, false);
}

export function GroupEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupEnum {
    return json as GroupEnum;
}

export function GroupEnumToJSON(value?: GroupEnum | null): any {
    return value as any;
}

