/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This serializer activates the tracking of
 * serialized objects.
 * It adds the `_represented` (not to use), the `represented`
 * and `reset` methods.
 * Important: it overrides the `to_representation` common method
 * of `Serializer` objects.
 * @export
 * @interface MetadataRequest
 */
export interface MetadataRequest {
    /**
     * 
     * @type {number}
     * @memberof MetadataRequest
     */
    graphObject: number;
    /**
     * 
     * @type {string}
     * @memberof MetadataRequest
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof MetadataRequest
     */
    value: any | null;
}

/**
 * Check if a given object implements the MetadataRequest interface.
 */
export function instanceOfMetadataRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "graphObject" in value;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function MetadataRequestFromJSON(json: any): MetadataRequest {
    return MetadataRequestFromJSONTyped(json, false);
}

export function MetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'graphObject': json['graph_object'],
        'key': json['key'],
        'value': json['value'],
    };
}

export function MetadataRequestToJSON(value?: MetadataRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'graph_object': value.graphObject,
        'key': value.key,
        'value': value.value,
    };
}

