/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * This serializer activates the tracking of
 * serialized objects.
 * It adds the `_represented` (not to use), the `represented`
 * and `reset` methods.
 * Important: it overrides the `to_representation` common method
 * of `Serializer` objects.
 * @export
 * @interface MetadataShortRequest
 */
export interface MetadataShortRequest {
    /**
     * 
     * @type {string}
     * @memberof MetadataShortRequest
     */
    key: string;
    /**
     * 
     * @type {any}
     * @memberof MetadataShortRequest
     */
    value: any | null;
}

/**
 * Check if a given object implements the MetadataShortRequest interface.
 */
export function instanceOfMetadataShortRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "key" in value;
    isInstance = isInstance && "value" in value;

    return isInstance;
}

export function MetadataShortRequestFromJSON(json: any): MetadataShortRequest {
    return MetadataShortRequestFromJSONTyped(json, false);
}

export function MetadataShortRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataShortRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function MetadataShortRequestToJSON(value?: MetadataShortRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'key': value.key,
        'value': value.value,
    };
}

