/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MetadataShortRequest } from './MetadataShortRequest';
import {
    MetadataShortRequestFromJSON,
    MetadataShortRequestFromJSONTyped,
    MetadataShortRequestToJSON,
} from './MetadataShortRequest';

/**
 * This serializer activates the tracking of
 * serialized objects.
 * It adds the `_represented` (not to use), the `represented`
 * and `reset` methods.
 * Important: it overrides the `to_representation` common method
 * of `Serializer` objects.
 * @export
 * @interface NodeRequest
 */
export interface NodeRequest {
    /**
     * 
     * @type {Array<MetadataShortRequest>}
     * @memberof NodeRequest
     */
    metadata?: Array<MetadataShortRequest>;
}

/**
 * Check if a given object implements the NodeRequest interface.
 */
export function instanceOfNodeRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NodeRequestFromJSON(json: any): NodeRequest {
    return NodeRequestFromJSONTyped(json, false);
}

export function NodeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'metadata': !exists(json, 'metadata') ? undefined : ((json['metadata'] as Array<any>).map(MetadataShortRequestFromJSON)),
    };
}

export function NodeRequestToJSON(value?: NodeRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'metadata': value.metadata === undefined ? undefined : ((value.metadata as Array<any>).map(MetadataShortRequestToJSON)),
    };
}

