/* tslint:disable */
/* eslint-disable */
/**
 * Situation API
 * Information System Knowledges
 *
 * The version of the OpenAPI document: 0.15.2 (0.15.2)
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TypesEnum = {
    Number: 'number',
    Array: 'array',
    Boolean: 'boolean',
    Object: 'object',
    String: 'string'
} as const;
export type TypesEnum = typeof TypesEnum[keyof typeof TypesEnum];


export function TypesEnumFromJSON(json: any): TypesEnum {
    return TypesEnumFromJSONTyped(json, false);
}

export function TypesEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypesEnum {
    return json as TypesEnum;
}

export function TypesEnumToJSON(value?: TypesEnum | null): any {
    return value as any;
}

